repos:
  - repo: local
    hooks:
      - id: touch_main.rs
        name: touch to enforce cargo clippy https://github.com/rust-lang/rust-clippy/issues/1495 .
        language: system
        entry: sh -c 'touch src/main.rs'
  - repo: https://github.com/doublify/pre-commit-rust
    rev: 55f347186aec7f2a4ec13c31effdb4b26512f2bc
    hooks:
      - id: clippy
        args: ['']
        name: cargo clippy https://github.com/rust-lang/rust-clippy/blob/master/README.md .
      - id: cargo-check
        name: cargo check https://doc.rust-lang.org/cargo/commands/cargo-check.html .